#ifndef __dlgAbout__
#define __dlgAbout__

/**
@file
Subclass of baseAbout, which is generated by wxFormBuilder.
*/

#include "FeatherUI.h"

//// end generated include

/** Implementing baseAbout */
class dlgAbout : public baseAbout
{
	protected:
		// Handlers for baseAbout events.
		void OnOK( wxCommandEvent& event );
	public:
		/** Constructor */
		dlgAbout( wxWindow* parent );
	//// end generated class members
	
};

#endif // __dlgAbout__
