#ifndef __MainFrame__
#define __MainFrame__

/**
@file
Subclass of baseMainFrame, which is generated by wxFormBuilder.
*/

#include "FeatherUI.h"

//// end generated include

/** Implementing baseMainFrame */
class MainFrame : public baseMainFrame
{
	protected:
		// Handlers for baseMainFrame events.
        void OnClose( wxCloseEvent& event );
		void OnFileNew( wxCommandEvent& event );
		void OnFileOpen( wxCommandEvent& event );
		void OnFileSave( wxCommandEvent& event );
		void OnFileSaveAs( wxCommandEvent& event );
		void OnFilePrint( wxCommandEvent& event );
		void OnFileExport( wxCommandEvent& event );
		void OnFileExit( wxCommandEvent& event );
		void OnToolsOptions( wxCommandEvent& event );
		void OnHelpContents( wxCommandEvent& event );
		void OnHelpContext( wxCommandEvent& event );
		void OnHelpUpdate( wxCommandEvent& event );
		void OnHelpAbout( wxCommandEvent& event );
	public:
		/** Constructor */
		MainFrame( wxWindow* parent );
	//// end generated class members

};

#endif // __MainFrame__
